# Generated by Django 3.2.6 on 2021-09-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snippetstests", "0007_translatablesnippet"),
    ]

    operations = [
        migrations.CreateModel(
            name="RocketSnippetWithConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
    ]
