# Generated by Django 4.2.10 on 2024-02-20 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0095_page_parent_locale'),
        ('snippetstests', '0011_nonautocompletesearchablesnippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='translatablesnippet',
            name='parent_locale',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale'),
        ),
    ]
