# Generated by Django 3.1.1 on 2020-10-02 17:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0010_document_file_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=None)], verbose_name='file'),
        ),
    ]
