# Generated by Django 2.1.3 on 2019-08-19 21:07

from django.db import migrations
import swapper


def initial_site(apps, schema_editor):
    ContentType = apps.get_model("contenttypes.ContentType")
    Page = apps.get_model("wagtailcore.Page")
    Site = apps.get_model(swapper.get_model_name("wagtailcore", "site"))

    page_content_type, created = ContentType.objects.get_or_create(
        model="page", app_label="wagtailcore"
    )

    # Get homepage
    homepage = Page.objects.get(
        title="Welcome to your new Wagtail site!",
        slug="home",
        content_type=page_content_type,
        path="00010001",
        depth=2,
        numchild=0,
        url_path="/home/",
    )

    # Create default site
    Site.objects.get_or_create(
        hostname="localhost", root_page_id=homepage.id, is_default_site=True
    )


def remove_initial_site(apps, schema_editor):
    """This function does nothing. The below code is commented out together
    with an explanation of why we don't need to bother reversing any of the
    initial data"""
    pass

    # This does not need to be deleted, Django takes care of it.
    # page_content_type = ContentType.objects.get(
    #     model='page',
    #     app_label='wagtailcore',
    # )

    # Do not reverse Site creation since other models might depend on it


class Migration(migrations.Migration):

    dependencies = []

    operations = [migrations.RunPython(initial_site, remove_initial_site)]
