# Generated by Django 5.2.15 on 2026-06-25 14:14

import django.db.models.deletion
import modelsearch.index
import uuid
import wagtail.models.content_types
import wagtail.models.preview
import wagtail.models.specific
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
    run_before = [
        ("wagtailcore", "0001_squashed_0016_change_page_url_path_to_text_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="BasePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255, unique=True)),
                ("depth", models.PositiveIntegerField()),
                ("numchild", models.PositiveIntegerField(default=0)),
                (
                    "live",
                    models.BooleanField(
                        default=True, editable=False, verbose_name="live"
                    ),
                ),
                (
                    "has_unpublished_changes",
                    models.BooleanField(
                        default=False,
                        editable=False,
                        verbose_name="has unpublished changes",
                    ),
                ),
                (
                    "first_published_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="first published at",
                    ),
                ),
                (
                    "last_published_at",
                    models.DateTimeField(
                        editable=False, null=True, verbose_name="last published at"
                    ),
                ),
                (
                    "go_live_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="go live date/time"
                    ),
                ),
                (
                    "expire_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="expiry date/time"
                    ),
                ),
                (
                    "expired",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="expired"
                    ),
                ),
                (
                    "locked",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="locked"
                    ),
                ),
                (
                    "locked_at",
                    models.DateTimeField(
                        editable=False, null=True, verbose_name="locked at"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The page title as you'd like it to be seen by the public",
                        max_length=255,
                        verbose_name="title",
                    ),
                ),
                ("draft_title", models.CharField(editable=False, max_length=255)),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        help_text="The name of the page as it will appear in URLs e.g http://domain.com/blog/[my-slug]/",
                        max_length=255,
                        verbose_name="slug",
                    ),
                ),
                (
                    "url_path",
                    models.TextField(
                        blank=True, editable=False, verbose_name="URL path"
                    ),
                ),
                (
                    "latest_revision_created_at",
                    models.DateTimeField(
                        editable=False,
                        null=True,
                        verbose_name="latest revision created at",
                    ),
                ),
                ("importance", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "alias_of",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="aliases",
                        to=settings.WAGTAIL_PAGE_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=models.SET(
                            wagtail.models.content_types.get_default_page_content_type
                        ),
                        related_name="pages",
                        to="contenttypes.contenttype",
                        verbose_name="content type",
                    ),
                ),
                (
                    "locked_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="locked_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="locked by",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_pages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "page",
                "verbose_name_plural": "pages",
                "permissions": [
                    ("bulk_delete_basepage", "Delete pages with children"),
                    ("lock_basepage", "Lock/unlock pages you've locked"),
                    ("publish_basepage", "Publish any page"),
                    ("unlock_basepage", "Unlock any page"),
                ],
            },
            bases=(
                wagtail.models.preview.PreviewableMixin,
                wagtail.models.specific.SpecificMixin,
                modelsearch.index.Indexed,
                models.Model,
            ),
        ),
    ]
