# Generated by Django 5.2.15 on 2026-06-26 12:55

import django.db.models.deletion
from django.db import migrations, models

from wagtail.models import BootstrapLocaleField, BootstrapTranslatableModel, BootstrapTranslationKeyField


class Migration(migrations.Migration):

    dependencies = [
        ("basepage", "0001_initial"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
    ]

    operations = [
        BootstrapLocaleField("basepage.BasePage"),
        BootstrapTranslationKeyField("basepage.BasePage"),
        BootstrapTranslatableModel("basepage.BasePage"),
    ]
