# Generated by Django 5.2.15 on 2026-06-26 14:26

from django.db import migrations

from wagtail.models import BootstrapTranslatableModel


class Migration(migrations.Migration):

    dependencies = [
        ("basepage", "0002_basepage_locale_and_revisions"),
    ]

    operations = [
        BootstrapTranslatableModel("basepage.BasePage"),
    ]
