# Generated by Django 5.2.15 on 2026-06-26 14:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("basepage", "0003_basepage_populate_locale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basepage",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.Locale",
                verbose_name="locale",
            ),
        ),
        migrations.AlterField(
            model_name="basepage",
            name="translation_key",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
