# Generated by Django 5.0.dev20230127120405 on 2023-01-27 12:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0083_workflowcontenttype"),
        ("tests", "0018_alter_streampage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="fullfeaturedsnippet",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
            ),
        ),
        migrations.AddField(
            model_name="fullfeaturedsnippet",
            name="translation_key",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterUniqueTogether(
            name="fullfeaturedsnippet",
            unique_together={("translation_key", "locale")},
        ),
    ]
