# Generated by Django 5.1.6 on 2025-07-14 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0057_featurecompletetoy_sort_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomLockTask",
            fields=[
                (
                    "task_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.task",
                    ),
                ),
            ],
            bases=("wagtailcore.task",),
        ),
    ]
