# Generated by Django 3.0.3 on 2020-03-10 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wagtailcore", "0048_add_default_workflows"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskstate",
            name="finished_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="finished_task_states",
                to=settings.AUTH_USER_MODEL,
                verbose_name="finished by",
            ),
        ),
    ]
