# The scripts for building the base images can be found in scripts/drone-images

build:
  flake8:
    image: python:3.5
    commands:
      - XDG_CACHE_HOME=/drone/pip-cache pip install flake8
      - flake8 wagtail
  jscs:
    image: node:4.2.4
    commands:
      - npm install -g eslint@"^2.2.0" --quiet
      - npm install -g eslint-plugin-react eslint-config-airbnb
      - eslint ./client
  scss-lint:
    image: wagtail-scss-lint
    commands:
      - scss-lint
  unittest:
    image: python:3.5
    commands:
      - XDG_CACHE_HOME=/drone/pip-cache pip install wheel
      - XDG_CACHE_HOME=/drone/pip-cache pip install -e .[testing,docs]
      - python runtests.py

cache:
  mount:
    - node_modules
    - /drone/pip-cache

notify:
  slack:
    webhook_url: https://hooks.slack.com/services/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
    channel: builds
    username: drone
    when:
      success: true
      failure: true
      change: true
