# The scripts for building the base images can be found in scripts/drone-images

build:
  flake8:
    image: python:3.5
    commands:
      - XDG_CACHE_HOME=/drone/pip-cache pip install flake8
      - flake8 wagtail
  jscs:
    image: node:4.2.4
    commands:
      - npm install -g jscs@"^1.12.0"
      - jscs ./wagtail
  scss-lint:
    image: wagtail-scss-lint
    commands:
      - scss-lint
  unittest:
    image: python:3.5
    commands:
      - XDG_CACHE_HOME=/drone/pip-cache pip install wheel
      - XDG_CACHE_HOME=/drone/pip-cache pip install -r requirements-dev.txt
      - XDG_CACHE_HOME=/drone/pip-cache pip install -e .
      - python runtests.py

cache:
  mount:
    - node_modules
    - /drone/pip-cache
