pipeline:
  lint_python:
    image: python:3.5
    group: lint
    commands:
      - XDG_CACHE_HOME=/drone/pip-cache pip install wheel
      - XDG_CACHE_HOME=/drone/pip-cache pip install -e .[testing]
      - flake8 wagtail
      - isort --check-only --diff --recursive wagtail
  lint_js:
    image: node:4.2.4
    group: lint
    commands:
      - npm install --quiet
      - npm run lint
      - npm run test:unit
  lint_scss:
    image: torchbox/scss-lint
    group: lint
    commands:
      - scss-lint
  unittest:
    image: python:3.5
    commands:
      - XDG_CACHE_HOME=/drone/pip-cache pip install wheel
      - XDG_CACHE_HOME=/drone/pip-cache pip install -e .[testing]
      - python -u runtests.py

cache:
  mount:
    - node_modules
    - /drone/pip-cache

notify:
  slack:
    webhook_url: https://hooks.slack.com/services/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
    channel: builds
    username: drone
    when:
      success: true
      failure: true
      change: true
