# The scripts for building the base images can be found in scripts/drone-images

build:
  flake8:
    image: wagtail-flake8
    commands:
      - flake8 wagtail
  jscs:
    image: wagtail-jscs
    commands:
      - jscs ./wagtail
  scss-lint:
    image: wagtail-scss-lint
    commands:
      - scss-lint
  unittest:
    image: python:3.5
    commands:
      - XDG_CACHE_HOME=/drone/pip-cache pip install wheel
      - XDG_CACHE_HOME=/drone/pip-cache pip install -r requirements-dev.txt
      - XDG_CACHE_HOME=/drone/pip-cache pip install -e .
      - python runtests.py

cache:
  mount:
    - /drone/pip-cache
