image: kaedroho/django-base
env:
 - DATABASE_HOST=postgres
 - ELASTICSEARCH_URL=http://elasticsearch:9200/
cache:
 - .tox
script:
 - pip install tox
 - tox
services:
 - postgres
 - dockerfile/elasticsearch
