version: 2
build:
  os: ubuntu-22.04
  tools:
    python: '3.11'
    nodejs: '22'
  jobs:
    post_install:
      - npm ci
    post_build:
      - npm run build-docs -- --out $READTHEDOCS_OUTPUT/html/reference/ui/client/
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
formats: all
sphinx:
  configuration: docs/conf.py
  fail_on_warning: True
search:
  ignore:
    # Ignore TypeDoc-generated docs as they can be noisy,
    # use TypeDoc's search mechanism for those pages instead.
    - reference/ui/client/*
  ranking:
    # Group release notes at the bottom of the search results instead of mixing
    # them with other pages.
    releases/*: -10
    # Except for the upgrading guide, which should have the normal rank.
    releases/upgrading.html: 0
