version: 2
build:
  os: ubuntu-22.04
  tools:
    python: '3.11'
    nodejs: '22'
  jobs:
    post_install:
      - npm install
    post_build:
      - npm run build-docs -- --out $READTHEDOCS_OUTPUT/html/reference/ui/client/
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
formats: all
sphinx:
  configuration: docs/conf.py
  fail_on_warning: True
search:
  ranking:
    releases/*: -1
    releases/upgrading.html: 0
