version: 2
build:
  os: ubuntu-22.04
  tools:
    python: '3.11'
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
sphinx:
  fail_on_warning: True
# Add these sections to specify the build formats
formats:
  - html
  - pdf
  - epub

# Custom commands for building PDF and EPUB
commands:
  - make html
  - make pdf
  - make epub