tools:
    external_code_coverage:
        timeout: 1200    # Timeout in seconds.
        runs: 5 # Wait for 6 code coverage submisisons. Corresponds to the Travis build matrix

checks:
    python:
        code_rating: true
        duplicate_code: true

filter:
    excluded_paths:
        - '*/test/*'
        - '*/south_migrations/*'
        - '*/migrations/*'
        - 'wagtail/vendor/*'
