# Generated by Django 2.1.3 on 2019-04-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='frame_count',
            field=models.IntegerField(editable=False, null=True, verbose_name='frame count'),
        ),
    ]
