# Generated by Django 2.2.9 on 2020-01-24 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text=None, related_name='image_set', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='tags'),
        ),
        migrations.AlterField(
            model_name='image',
            name='uploaded_by_user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_set', to=settings.AUTH_USER_MODEL, verbose_name='uploaded by user'),
        ),
    ]
