# Generated by Django 4.0.3 on 2022-04-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0023_add_choose_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="file_hash",
            field=models.CharField(
                blank=True, db_index=True, editable=False, max_length=40
            ),
        ),
    ]
