# Generated by Django 4.2.7 on 2024-03-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_description',
            field=models.CharField(default='image description', max_length=255, verbose_name='image description'),
        ),
    ]
