# Generated by Django 5.2.4 on 2025-08-18 10:23

from django.db import migrations, models
import django.utils.timezone


def copy_created_to_updated(apps, schema_editor):
    Image = apps.get_model('wagtailimages', 'Image')
    for image in Image.objects.all():
        image.updated_at = image.created_at
        image.save(update_fields=['updated_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='updated_at',
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                verbose_name='updated at',
                null=True,   # allow NULL during migration
            ),
        ),
        migrations.RunPython(copy_created_to_updated, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='image',
            name='updated_at',
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                verbose_name='updated at',
            ),
        ),
    ]
