# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-24 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailsearchpromotions', '0002_capitalizeverbose'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchpromotion',
            name='external_page',
            field=models.URLField(blank=True, help_text='A page not on this site'),
        ),
        migrations.AddField(
            model_name='searchpromotion',
            name='external_page_title',
            field=models.CharField(blank=True, help_text='Title for a page not on this site', max_length=255),
        ),
        migrations.AlterField(
            model_name='searchpromotion',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Page', verbose_name='page'),
        ),
    ]
