# Generated by Django 5.2.11 on 2026-02-14 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailsearchpromotions', '0007_searchpromotion_external_link_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='query',
            options={'verbose_name': 'query', 'verbose_name_plural': 'queries'},
        ),
    ]
