# Generated by Django 2.2.6 on 2020-02-16 21:18

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_auto_20200216_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
