# Generated by Django 2.2.6 on 2020-02-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0004_auto_20200216_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpagerelatedlink',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpagerelatedlink',
            name='url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
