# Generated by Django 5.2.15 on 2026-07-02 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageViewRestriction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True,
                        help_text="Shared passwords should not be used to protect sensitive content. Anyone who has this password will be able to view the content.",
                        max_length=255,
                        verbose_name="shared password",
                    ),
                ),
                (
                    "restriction_type",
                    models.CharField(
                        choices=[
                            ("none", "Public"),
                            ("password", "Private, accessible with a shared password"),
                            ("login", "Private, accessible to any logged-in users"),
                            (
                                "groups",
                                "Private, accessible to users in specific groups",
                            ),
                            ("admin", "Private, accessible to superusers"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True, to="auth.group", verbose_name="groups"
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="view_restrictions",
                        to="wagtailcore.page",
                        verbose_name="page",
                    ),
                ),
            ],
            options={
                "verbose_name": "page view restriction",
                "verbose_name_plural": "page view restrictions",
                "abstract": False,
            },
        ),
    ]
