# Generated by Django 4.0.5 on 2022-07-20 14:53

from django.db import migrations, models
import django.db.models.deletion
import swapper


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0076_modellogentry_revision"),
        ("tests", "0005_previewablemodel_nonpreviewablemodel_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MultiPreviewModesPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=swapper.get_model_name("wagtailcore", "Page"),
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(swapper.get_model_name("wagtailcore", "Page"),),
        ),
    ]
