# Generated by Django 4.1.7 on 2023-03-13 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0022_variousondeletemodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="snippetchoosermodel",
            name="full_featured",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tests.fullfeaturedsnippet",
                verbose_name="Chosen snippet",
            ),
        ),
    ]
