# Generated by Django 4.2.4 on 2023-08-15 14:10

from django.db import migrations, models

import wagtail.test.testapp.models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0025_alter_importantpagesgenericsetting_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureCompleteToy",
            fields=[
                (
                    "strid",
                    models.CharField(
                        primary_key=True,
                        default=wagtail.test.testapp.models.random_quotable_pk,
                        max_length=255,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
    ]
