# Generated by Django 4.0.10 on 2023-07-08 22:18

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.test.testapp.models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0025_alter_importantpagesgenericsetting_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="streampage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("text", wagtail.blocks.CharBlock()),
                    (
                        "choice",
                        wagtail.blocks.ChoiceBlock(
                            choices=wagtail.test.testapp.models.get_callable_choices,
                            required=False,
                        ),
                    ),
                    ("rich_text", wagtail.blocks.RichTextBlock()),
                    ("image", wagtail.test.testapp.models.ExtendedImageChooserBlock()),
                    (
                        "product",
                        wagtail.blocks.StructBlock(
                            [
                                ("name", wagtail.blocks.CharBlock()),
                                ("price", wagtail.blocks.CharBlock()),
                            ]
                        ),
                    ),
                    ("raw_html", wagtail.blocks.RawHTMLBlock()),
                    (
                        "books",
                        wagtail.blocks.StreamBlock(
                            [
                                ("title", wagtail.blocks.CharBlock()),
                                ("author", wagtail.blocks.CharBlock()),
                            ]
                        ),
                    ),
                    (
                        "title_list",
                        wagtail.blocks.ListBlock(wagtail.blocks.CharBlock()),
                    ),
                ],
                use_json_field=True,
            ),
        ),
    ]
