# Generated by Django 4.2.4 on 2023-08-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0025_alter_importantpagesgenericsetting_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureCompleteToy",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
    ]
