# Generated by Django 4.0.10 on 2023-10-09 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("tests", "0029_variousondeletemodel_cascading_toy"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurgeRevisionsProtectedTestModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "revision",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="wagtailcore.revision",
                    ),
                ),
            ],
        ),
    ]
