# Generated by Django 4.2.7 on 2023-11-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0030_purgerevisionsprotectedtestmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchTestModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField()),
            ],
        ),
    ]
