# Generated by Django 4.2.3 on 2023-07-19 12:59

from django.db import migrations, models
import django.db.models.deletion
import swapper


page_model_name = swapper.split(swapper.get_model_name("wagtailcore", "Page"))[1]
parent_rel_name = f"{page_model_name.lower()}_ptr"


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0088_fix_log_entry_json_timestamps"),
        ("tests", "0031_searchtestmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomPermissionPage",
            fields=[
                (
                    parent_rel_name,
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=swapper.get_model_name("wagtailcore", "Page"),
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(swapper.get_model_name("wagtailcore", "Page"),),
        ),
    ]
