# Generated by Django 4.2.7 on 2024-02-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0033_customcopyformpage"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomPermissionModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(default="Tailwag")),
            ],
            options={
                "verbose_name": "ADVANCED permission model",
                "verbose_name_plural": "ADVANCED permission models",
                "permissions": [
                    ("can_start_trouble", "Can start trouble"),
                    ("cause_chaos", "Cause chaos for advanced permission model"),
                    ("change_text", "Change text"),
                    ("control", "Manage custom permission model"),
                ],
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "bulk_update",
                ),
            },
        ),
    ]
