# Generated by Django 4.2.7 on 2024-02-12 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0033_customcopyformpage"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelWithVerboseName",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Custom verbose name",
                "verbose_name_plural": "Custom verbose names",
            },
        ),
    ]
