# Generated by Django 4.0.7 on 2022-09-24 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0034_custompermissionmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtremeChallengeEventPage",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("tests.eventpage",),
        ),
        migrations.CreateModel(
            name="FoodieEventPage",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("tests.eventpage",),
        ),
        migrations.CreateModel(
            name="ProxyAdvert",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("tests.advert",),
        ),
    ]
