# Generated by Django 4.2.13 on 2024-06-12 12:06

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.search.index


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0037_testpermissionedgenericsetting_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                (
                    "kind",
                    models.CharField(
                        choices=[("twitter", "Twitter"), ("facebook", "Facebook")],
                        max_length=30,
                    ),
                ),
                (
                    "person",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_links",
                        to="tests.personpage",
                        verbose_name="Person",
                    ),
                ),
            ],
            options={
                "verbose_name": "social link",
                "verbose_name_plural": "social links",
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
