# Generated by Django 4.2.11 on 2024-05-10 12:41

from django.db import migrations, models
import django.db.models.deletion
import swapper


page_model_name = swapper.split(swapper.get_model_name("wagtailcore", "Page"))[1]
parent_rel_name = f"{page_model_name.lower()}_ptr"


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0093_uploadedfile"),
        ("tests", "0039_alter_eventcategory_locale_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NoCreatableSubpageTypesPage",
            fields=[
                (
                    parent_rel_name,
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=swapper.get_model_name("wagtailcore", "Page"),
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(swapper.get_model_name("wagtailcore", "Page"),),
        ),
        migrations.CreateModel(
            name="NoSubpageTypesPage",
            fields=[
                (
                    parent_rel_name,
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=swapper.get_model_name("wagtailcore", "Page"),
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(swapper.get_model_name("wagtailcore", "Page"),),
        ),
    ]
