# Generated by Django 5.1.1 on 2024-10-11 20:40

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0043_customimage_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="streampage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("text", 0),
                    ("rich_text", 1),
                    ("image", 2),
                    ("product", 3),
                    ("raw_html", 4),
                    ("books", 5),
                    ("title_list", 6),
                    ("image_with_alt", 10),
                ],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: ("wagtail.blocks.RichTextBlock", (), {}),
                    2: (
                        "wagtail.test.testapp.models.ExtendedImageChooserBlock",
                        (),
                        {},
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("name", 0), ("price", 0)]],
                        {},
                    ),
                    4: ("wagtail.blocks.RawHTMLBlock", (), {}),
                    5: (
                        "wagtail.blocks.StreamBlock",
                        [[("title", 0), ("author", 0)]],
                        {},
                    ),
                    6: ("wagtail.blocks.ListBlock", (0,), {}),
                    7: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": True},
                    ),
                    8: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "label": "Image is decorative",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Alt text", "required": False},
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 7), ("decorative", 8), ("alt_text", 9)]],
                        {},
                    ),
                },
            ),
        ),
    ]
