# Generated by Django 5.1.1 on 2024-10-11 20:40

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0044_custompreviewsizesmodel_custompreviewsizespage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="streampage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("text", 0),
                    ("rich_text", 1),
                    ("image", 2),
                    ("product", 3),
                    ("raw_html", 4),
                    ("books", 5),
                    ("title_list", 6),
                    ("image_with_alt", 7),
                ],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: ("wagtail.blocks.RichTextBlock", (), {}),
                    2: (
                        "wagtail.test.testapp.models.ExtendedImageChooserBlock",
                        (),
                        {},
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("name", 0), ("price", 0)]],
                        {},
                    ),
                    4: ("wagtail.blocks.RawHTMLBlock", (), {}),
                    5: (
                        "wagtail.blocks.StreamBlock",
                        [[("title", 0), ("author", 0)]],
                        {},
                    ),
                    6: ("wagtail.blocks.ListBlock", (0,), {}),
                    7: ("wagtail.images.blocks.ImageBlock", [], {}),
                },
            ),
        ),
    ]
