# Generated by Django 5.1.6 on 2025-03-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0047_advertwithcustomuuidprimarykey_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="featurecompletetoy",
            name="sort_order",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
