# Generated by Django 5.1.6 on 2025-03-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0047_advertwithcustomuuidprimarykey_page"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="featurecompletetoy",
            options={
                "ordering": ["sort_order"],
                "permissions": [("can_set_release_date", "Can set release date")],
            },
        ),
        migrations.AddField(
            model_name="featurecompletetoy",
            name="sort_order",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
