# Generated by Django 5.0.12 on 2025-03-20 22:31

import django.db.models.deletion
from django.db import migrations, models
import swapper


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0048_requireddatepage"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromotionalPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=swapper.get_model_name("wagtailcore", "Page"),
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(swapper.get_model_name("wagtailcore", "Page"),),
        ),
    ]
