# Generated by Django 5.2 on 2025-05-01 18:42

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0051_userapprovaltaskstate_userapprovaltask"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagewithexcludedcopyfield",
            name="special_stream",
            field=wagtail.fields.StreamField(
                [("item", 0)],
                block_lookup={0: ("wagtail.blocks.CharBlock", (), {})},
                default=[("item", "default item")],
            ),
        ),
        migrations.CreateModel(
            name="ExcludedCopyPageNote",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("note", models.CharField(max_length=255)),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="special_notes",
                        to="tests.pagewithexcludedcopyfield",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
