# Generated by Django 5.2.5 on 2025-08-14 19:05

import django.db.models.deletion
from django.db import migrations, models
import swapper

import wagtail.fields
import wagtail.test.testapp.fields


page_model_name = swapper.split(swapper.get_model_name("wagtailcore", "Page"))[1]
parent_rel_name = f"{page_model_name.lower()}_ptr"


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0055_previewable_settings"),
        ("wagtailcore", "0095_groupsitepermission"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentableJSONPage",
            fields=[
                (
                    parent_rel_name,
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=swapper.get_model_name("wagtailcore", "Page"),
                    ),
                ),
                (
                    "commentable_body",
                    wagtail.test.testapp.fields.CommentableJSONField(),
                ),
                ("uncommentable_body", models.JSONField()),
                (
                    "stream_body",
                    wagtail.fields.StreamField(
                        [("text", 0)],
                        block_lookup={0: ("wagtail.blocks.CharBlock", (), {})},
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(swapper.get_model_name("wagtailcore", "Page"),),
        ),
    ]
