# Generated by Django 5.2.5 on 2025-08-14 19:05

import django.db.models.deletion
from django.db import migrations, models

import wagtail.fields
import wagtail.test.testapp.fields


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0055_previewable_settings"),
        ("wagtailcore", "0095_groupsitepermission"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentableJSONPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "commentable_body",
                    wagtail.test.testapp.fields.CommentableJSONField(),
                ),
                ("uncommentable_body", models.JSONField()),
                (
                    "stream_body",
                    wagtail.fields.StreamField(
                        [("text", 0)],
                        block_lookup={0: ("wagtail.blocks.CharBlock", (), {})},
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
