# Generated by Django 5.2.4 on 2025-08-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0055_previewable_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customdocument',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='customdocumentwithauthor',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='customrestaurantdocument',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='customimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='customimagefilepath',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='customimagewithauthor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='customrestaurantimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='updated at'),
        ),
    ]
