# Generated by Django 5.2.7 on 2025-11-14 04:38

import django.db.models.deletion
from django.db import migrations, models
import swapper


page_model_name = swapper.split(swapper.get_model_name("wagtailcore", "Page"))[1]
parent_rel_name = f"{page_model_name.lower()}_ptr"


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0058_customlocktask'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoPromotePage',
            fields=[
                (parent_rel_name, models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=swapper.get_model_name("wagtailcore", "Page"))),
            ],
            options={
                'abstract': False,
            },
            bases=(swapper.get_model_name("wagtailcore", "Page"),),
        ),
    ]
