# Generated by Django 6.0.7 on 2026-08-06 13:11

import uuid

import django.db.models.deletion
import modelcluster.fields
import modelsearch.index
from django.db import migrations, models

import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0061_revisablecluster_revisableclusterchild"),
        ("wagtaildocs", "0014_alter_document_file_size"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="UUIDSnippetWithRelations",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                ("subtitle", models.CharField(blank=True, max_length=255)),
                ("intro", models.CharField(blank=True, max_length=255)),
                (
                    "rich_body",
                    wagtail.fields.RichTextField(
                        blank=True,
                        features=["image","italic", "link", "quotation", "embed"],
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("text", 0),
                            ("rich_text", 1),
                            ("image", 2),
                            ("product", 3),
                            ("raw_html", 4),
                            ("books", 5),
                            ("title_list", 6),
                            ("image_with_alt", 7),
                        ],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {}),
                            1: ("wagtail.blocks.RichTextBlock", (), {}),
                            2: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("name", 0), ("price", 0)]],
                                {},
                            ),
                            4: ("wagtail.blocks.RawHTMLBlock", (), {}),
                            5: (
                                "wagtail.blocks.StreamBlock",
                                [[("title", 0), ("author", 0)]],
                                {},
                            ),
                            6: ("wagtail.blocks.ListBlock", (0,), {}),
                            7: ("wagtail.images.blocks.ImageBlock", [], {}),
                        },
                    ),
                ),
                (
                    "feed_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name="UUIDSnippetWithRelationsSection",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("link_external", models.URLField(blank=True)),
                ("internal_note", models.CharField(blank=True, max_length=255)),
                (
                    "link_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtaildocs.document",
                    ),
                ),
                (
                    "snippet",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="tests.uuidsnippetwithrelations",
                    ),
                ),
            ],
        ),
    ]
