# Generated by Django 6.0.6 on 2026-06-30 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0061_revisablecluster_revisableclusterchild'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelWithCustomExtractReferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('related', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tests.modelwithcustomextractreferences')),
            ],
        ),
    ]
