# Generated by Django 6.0.2 on 2026-02-25 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0061_revisablecluster_revisableclusterchild'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePermissionSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_permission_snippets', to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'site permission snippet',
                'verbose_name_plural': 'site permission snippets',
            },
        ),
    ]
