# Generated by Django 6.0.8 on 2026-08-25 07:57

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0062_uuidsnippetwithrelations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streampage',
            name='body',
            field=wagtail.fields.StreamField([('text', 0), ('rich_text', 1), ('image', 2), ('product', 3), ('raw_html', 4), ('books', 5), ('title_list', 6), ('image_with_alt', 7), ('table', 8)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.test.testapp.models.ExtendedImageChooserBlock', (), {}), 3: ('wagtail.blocks.StructBlock', [[('name', 0), ('price', 0)]], {}), 4: ('wagtail.blocks.RawHTMLBlock', (), {}), 5: ('wagtail.blocks.StreamBlock', [[('title', 0), ('author', 0)]], {}), 6: ('wagtail.blocks.ListBlock', (0,), {}), 7: ('wagtail.images.blocks.ImageBlock', [], {}), 8: ('wagtail.contrib.table_block.blocks.TableBlock', (), {})}),
        ),
    ]
