# Generated by Django 6.0.6 on 2026-06-30 07:28

import django.db.models.deletion
import wagtail.test.testapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0062_modelwithcustomextractreferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelWithCustomForeignKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('related', wagtail.test.testapp.models.CustomForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests.modelwithcustomforeignkey')),
            ],
        ),
        migrations.DeleteModel(
            name='ModelWithCustomExtractReferences',
        ),
    ]
