# Generated by Django 6.1.1 on 2026-09-10 17:35

import django.db.models.deletion
import wagtail.contrib.forms.models
from django.conf import settings
from django.db import migrations, models
import swapper


page_model_name = swapper.split(swapper.get_model_name("wagtailcore", "Page"))[1]
parent_rel_name = f"{page_model_name.lower()}_ptr"


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0063_alter_streampage_body'),
        ('wagtailcore', '0098_apitoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadlessForm',
            fields=[
                (parent_rel_name, models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=swapper.get_model_name("wagtailcore", "Page"))),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.contrib.forms.models.FormMixin, swapper.get_model_name("wagtailcore", "Page")),
        ),
    ]
