# Generated by Django 6.1.1 on 2026-09-26 18:48

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0001_squashed_0065_instantiate_headless_form"),
    ]

    operations = [
        migrations.CreateModel(
            name="UUIDSnippetWithRelationsSectionLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("url", models.URLField()),
                (
                    "section",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="tests.uuidsnippetwithrelationssection",
                    ),
                ),
            ],
        ),
    ]
