# Generated by Django 6.1.1 on 2026-09-26 18:53

from django.db import migrations

import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0066_uuidsnippetwithrelationssectionlink"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uuidsnippetwithrelations",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("text", 0),
                    ("rich_text", 1),
                    ("image", 2),
                    ("product", 3),
                    ("raw_html", 4),
                    ("books", 5),
                    ("title_list", 6),
                    ("image_with_alt", 7),
                    ("typed_table", 9),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: ("wagtail.blocks.RichTextBlock", (), {}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("name", 0), ("price", 0)]],
                        {},
                    ),
                    4: ("wagtail.blocks.RawHTMLBlock", (), {}),
                    5: (
                        "wagtail.blocks.StreamBlock",
                        [[("title", 0), ("author", 0)]],
                        {},
                    ),
                    6: ("wagtail.blocks.ListBlock", (0,), {}),
                    7: ("wagtail.images.blocks.ImageBlock", [], {}),
                    8: ("wagtail.blocks.IntegerBlock", (), {}),
                    9: (
                        "wagtail.contrib.typed_table_block.blocks.TypedTableBlock",
                        [[("text", 0), ("number", 8)]],
                        {},
                    ),
                },
            ),
        ),
    ]
