# Generated by Django 4.0.2 on 2022-05-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0070_tagged_restaurant_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customrestaurantimage",
            name="file_hash",
            field=models.CharField(
                blank=True, db_index=True, editable=False, max_length=40
            ),
        ),
    ]
