# Generated by Django 4.0.4 on 2022-05-12 12:27
import json
from django.conf import settings
from django.db import migrations


def test_streamvalue_migration_behaviour(apps, schema_editor):
    JSONStreamModel = apps.get_model("tests.StreamModel")
    obj = JSONStreamModel.objects.create(
        body=json.dumps(
            [
                {"type": "text", "value": "foo"},
                {"type": "rich_text", "value": "<p>bar</p>"},
                {"type": "unknown", "value": "baz"},
            ]
        ),
    )

    # Determine whether the StreamValue.raw_data includes the 'unknown' block
    unknown_block_value_found = False
    for block in obj.body.raw_data:
        if block["type"] == "unknown":
            unknown_block_value_found = True

    obj.delete()

    # By default, StreamValue.raw_data does not include values without a
    # corresponding block definition. So, if 'unknown' was found, that must
    # mean that the relevant setting is set to True.
    setting_value = getattr(
        settings,
        "WAGTAIL_STREAMFIELD_PRESERVE_UNRECOGNISED_BLOCK_VALUES_IN_MIGRATIONS",
        False,
    )

    assert unknown_block_value_found == setting_value


class Migration(migrations.Migration):

    dependencies = [
        (
            "tests",
            "0073_revisablechildmodel_secret_text",
        ),
    ]

    operations = [
        migrations.RunPython(
            test_streamvalue_migration_behaviour, migrations.RunPython.noop
        ),
    ]
