# Generated by Django 2.0.8 on 2018-08-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='streammodel',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
