# Generated by Django 4.0.7 on 2022-10-10 17:53

from django.db import migrations


class DeleteModelIfExists(migrations.DeleteModel):
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = from_state.apps.get_model(app_label, self.name)
        table_name = model._meta.db_table
        if table_name in schema_editor.connection.introspection.table_names():
            super().database_forwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailsearch", "0006_customise_indexentry"),
    ]

    operations = [
        DeleteModelIfExists(
            name="EditorsPick",
        ),
    ]
