# Generated by Django 2.0 on 2018-01-17 01:03

from django.db import migrations, models
import wagtail.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailusers', '0006_userprofile_prefered_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=wagtail.users.models.upload_avatar_to, verbose_name='profile picture'),
        ),
    ]
