# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailusers', '0007_userprofile_current_time_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=wagtail.users.models.upload_avatar_to, verbose_name='Upload your custom avatar'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar_choice',
            field=models.CharField(choices=[('default', 'Default'), ('custom', 'Custom'), ('gravatar', 'Gravatar')], default='default', max_length=10, verbose_name='Select profile picture type'),
        ),
    ]
