# Generated by Django 4.0.5 on 2022-10-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailusers", "0010_userprofile_updated_comments_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="dismissibles",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
