from wagtail.admin.views.pages.copy import *  # noqa
from wagtail.admin.views.pages.create import *  # noqa
from wagtail.admin.views.pages.delete import *  # noqa
from wagtail.admin.views.pages.edit import *  # noqa
from wagtail.admin.views.pages.history import *  # noqa
from wagtail.admin.views.pages.listing import *  # noqa
from wagtail.admin.views.pages.lock import *  # noqa
from wagtail.admin.views.pages.moderation import *  # noqa
from wagtail.admin.views.pages.move import *  # noqa
from wagtail.admin.views.pages.ordering import *  # noqa
from wagtail.admin.views.pages.preview import *  # noqa
from wagtail.admin.views.pages.revisions import *  # noqa
from wagtail.admin.views.pages.search import *  # noqa
from wagtail.admin.views.pages.unpublish import *  # noqa
from wagtail.admin.views.pages.usage import *  # noqa
from wagtail.admin.views.pages.workflow import *  # noqa
