# Generated by Django 2.1.7 on 2019-04-03 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0043_simpleproxypage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyAdvert',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('tests.advert',),
        ),
    ]
