# Generated by Django 2.1.7 on 2019-04-26 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0044_proxyadvert'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleProxyPageDeux',
            fields=[
            ],
            options={
                'indexes': [],
                'proxy': True,
            },
            bases=('tests.simplepage',),
        ),
    ]
