# Generated by Django 2.2.8 on 2020-01-03 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0042_index_on_pagerevision_approved_go_live_at'),
        ('tests', '0045_add_formsubmission_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimplePageWithGeneratedTitle',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
