# Generated by Django 3.0.6 on 2020-06-03 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0051_tag_verbose_name'),
        ('tests', '0043_streammodel_gallery'),
    ]

    operations = [
    ]
