# Generated by Django 2.2.13 on 2020-08-18 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0054_simpletask'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdocument',
            name='defaulted_field',
            field=models.IntegerField(default=1),
        ),
    ]
