# Generated by Django 3.0.8 on 2020-07-30 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0054_simpletask'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['sort_order'], 'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
    ]
