# Generated by Django 3.1.1 on 2020-09-28 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0057_page_locale_fields_notnull'),
        ('tests', '0056_streampage_nested_streamblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlagLocaleComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.CharField(blank=True, choices=[('union-jack', 'Union Jack'), ('tricolore', 'Tricolore')], max_length=255)),
                ('locale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flag', to='wagtailcore.locale')),
            ],
        ),
    ]
