# Generated by Django 2.2.dev20181026000358 on 2018-10-27 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailsearch', '0003_remove_editors_pick'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='querydailyhits',
            options={'verbose_name': 'Query Daily Hits', 'verbose_name_plural': 'Query Daily Hits'},
        ),
    ]
