# Generated by Django 2.2.16 on 2021-04-13 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailadmin', '0003_admin_managed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'default_permissions': [], 'permissions': [('access_admin', 'Can access Wagtail admin'), ('submit_translation', 'Can submit translations')]},
        ),
    ]
