# Generated by Django 5.1a1 on 2024-07-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailadmin", "0004_editingsession"),
    ]

    operations = [
        migrations.AddField(
            model_name="editingsession",
            name="is_editing",
            field=models.BooleanField(default=False),
        ),
    ]
