# Generated by Django 4.0.4 on 2022-05-31 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modeladmintest", "0010_translatablebook"),
    ]

    operations = [
        migrations.CreateModel(
            name="Enemy",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
            ],
        ),
    ]
