# Generated by Django 4.0.8 on 2022-12-17 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modeladmintest", "0012_publisher_latest_revision"),
    ]

    operations = [
        migrations.CreateModel(
            name="TokenWithIcon",
            fields=[
                (
                    "key",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
            ],
        ),
    ]
