# Generated by Django 4.0.10 on 2023-03-27 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtaildocs", "0012_uploadeddocument"),
        ("modeladmintest", "0012_publisher_latest_revision"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="extract_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="wagtaildocs.document",
            ),
        ),
    ]
