# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-11 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0015_fill_filter_spec_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendition',
            name='filter_spec',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='rendition',
            unique_together=set([('image', 'filter_spec', 'focal_point_key')]),
        ),
    ]
