# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 17:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0016_deprecate_rendition_filter_relation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendition',
            name='filter',
        ),
    ]
