# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-16 14:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0016_deprecate_rendition_filter_relation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendition',
            name='filter',
        ),
        migrations.DeleteModel(
            name='Filter',
        ),
    ]
