# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0001_initial'),
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupCollectionManagementPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[('add', 'Add/edit collections you own'), ('edit', 'Edit any collection'), ('bulk_delete', 'Delete collections with children')], max_length=20, verbose_name='permission type')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_manage_permissions', to='wagtailcore.Collection', verbose_name='page')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_manage_permissions', to='auth.Group', verbose_name='group')),
            ],
            options={
                'verbose_name_plural': 'group manage collection permissions',
                'verbose_name': 'group manage collection permission',
            },
        ),
        migrations.AlterUniqueTogether(
            name='groupcollectionmanagementpermission',
            unique_together=set([('group', 'collection', 'permission_type')]),
        ),
    ]
