# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0033_collectionviewrestriction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionviewrestriction',
            name='groups',
            field=models.ManyToManyField(blank=True, to='auth.Group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='pageviewrestriction',
            name='groups',
            field=models.ManyToManyField(blank=True, to='auth.Group', verbose_name='groups'),
        ),
    ]
