# Generated by Django 5.2 on 2025-04-13 08:21

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="SampleModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    wagtail.fields.StreamField(
                        [
                            ("char1", 0),
                            ("char2", 0),
                            ("simplestruct", 1),
                            ("simplestream", 2),
                            ("simplelist", 3),
                            ("nestedstruct", 4),
                            ("nestedstream", 5),
                            ("nestedlist_struct", 6),
                            ("nestedlist_stream", 7),
                        ],
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {}),
                            1: (
                                "wagtail.blocks.StructBlock",
                                [[("char1", 0), ("char2", 0)]],
                                {},
                            ),
                            2: (
                                "wagtail.blocks.StreamBlock",
                                [[("char1", 0), ("char2", 0)]],
                                {},
                            ),
                            3: ("wagtail.blocks.ListBlock", (0,), {}),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("char1", 0),
                                        ("stream1", 2),
                                        ("struct1", 1),
                                        ("list1", 3),
                                    ]
                                ],
                                {},
                            ),
                            5: (
                                "wagtail.blocks.StreamBlock",
                                [
                                    [
                                        ("char1", 0),
                                        ("stream1", 2),
                                        ("struct1", 1),
                                        ("list1", 3),
                                    ]
                                ],
                                {},
                            ),
                            6: ("wagtail.blocks.ListBlock", (1,), {}),
                            7: ("wagtail.blocks.ListBlock", (2,), {}),
                        },
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SamplePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "content",
                    wagtail.fields.StreamField(
                        [
                            ("char1", 0),
                            ("char2", 0),
                            ("simplestruct", 1),
                            ("simplestream", 2),
                            ("simplelist", 3),
                            ("nestedstruct", 4),
                            ("nestedstream", 5),
                            ("nestedlist_struct", 6),
                            ("nestedlist_stream", 7),
                        ],
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {}),
                            1: (
                                "wagtail.blocks.StructBlock",
                                [[("char1", 0), ("char2", 0)]],
                                {},
                            ),
                            2: (
                                "wagtail.blocks.StreamBlock",
                                [[("char1", 0), ("char2", 0)]],
                                {},
                            ),
                            3: ("wagtail.blocks.ListBlock", (0,), {}),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("char1", 0),
                                        ("stream1", 2),
                                        ("struct1", 1),
                                        ("list1", 3),
                                    ]
                                ],
                                {},
                            ),
                            5: (
                                "wagtail.blocks.StreamBlock",
                                [
                                    [
                                        ("char1", 0),
                                        ("stream1", 2),
                                        ("struct1", 1),
                                        ("list1", 3),
                                    ]
                                ],
                                {},
                            ),
                            6: ("wagtail.blocks.ListBlock", (1,), {}),
                            7: ("wagtail.blocks.ListBlock", (2,), {}),
                        },
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
