# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-16 10:13
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0007_merge'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='document',
            managers=[
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
