# Generated by Django 1.11.1 on 2017-06-01 11:03
import swapper
from django.db import migrations
from django.db.models import F


def forwards_func(apps, schema_editor):
    if swapper.is_swapped("wagtailcore", "Page"):
        # This backfills last_published_at on rows that predate that field's
        # existence. Custom page models are a Wagtail 8.0+ feature, so a
        # swapped-in model was always defined with this field present and
        # has no pre-existing rows to backfill.
        return

    Page = apps.get_model("wagtailcore", "Page")
    Page.objects.filter(has_unpublished_changes=False).update(
        last_published_at=F("latest_revision_created_at")
    )


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0035_page_last_published_at"),
    ]

    operations = [
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
