# Generated by Django 1.10.2 on 2017-01-20 15:34
import swapper
from django.db import migrations, models
from django.db.models import F


def draft_title(apps, schema_editor):
    if swapper.is_swapped("wagtailcore", "Page"):
        # This backfills draft_title on rows that predate that field's
        # existence. Custom page models are a Wagtail 8.0+ feature, so a
        # swapped-in model was always defined with this field present and
        # has no pre-existing rows to backfill.
        return

    Page = apps.get_model("wagtailcore", "Page")

    Page.objects.all().update(draft_title=F("title"))


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0039_collectionviewrestriction"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="draft_title",
            field=models.CharField(default="", editable=False, max_length=255),
            preserve_default=False,
        ),
        migrations.RunPython(draft_title, migrations.RunPython.noop),
    ]
