# Generated by Django 2.2.10 on 2020-07-13 10:13

import swapper
from django.db import migrations

from wagtail.models import BootstrapTranslatableModel


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0055_page_locale_fields"),
    ]

    if swapper.is_swapped("wagtailcore", "Page"):
        # This backfills translation_key/locale on rows that predate those
        # fields' existence. Custom page models are a Wagtail 8.0+ feature,
        # so a swapped-in model was always defined with these fields present
        # and has no pre-existing rows to backfill.
        operations = []
    else:
        operations = [
            BootstrapTranslatableModel("wagtailcore.Page"),
        ]
