# Generated by Django 4.0.2 on 2022-02-24 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0068_log_entry_empty_object"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modellogentry",
            name="data_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="pagelogentry",
            name="data_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RenameField(
            model_name="modellogentry",
            old_name="data_json",
            new_name="data",
        ),
        migrations.RenameField(
            model_name="pagelogentry",
            old_name="data_json",
            new_name="data",
        ),
    ]
