# Generated by Django 4.0.2 on 2022-03-18 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0069_log_entry_jsonfield"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="site",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default_site", True)),
                fields=("is_default_site",),
                name="unique_in_default_site",
            ),
        ),
    ]
