# Generated by Django 4.0.3 on 2022-04-26 12:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wagtailcore", "0069_log_entry_jsonfield"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PageRevision",
            new_name="Revision",
        ),
    ]
