# Generated by Django 4.0.3 on 2022-04-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0070_rename_pagerevision_revision"),
    ]

    operations = [
        migrations.AlterField(
            model_name="revision",
            name="page",
            field=models.CharField(max_length=255, verbose_name="object id"),
        ),
    ]
