# Generated by Django 4.0.3 on 2022-04-26 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0071_alter_revision_page"),
    ]

    operations = [
        migrations.RenameField(
            model_name="revision",
            old_name="page",
            new_name="object_id",
        ),
    ]
