# Generated by Django 4.0.3 on 2022-04-26 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("wagtailcore", "0072_rename_page_revision_object_id"),
    ]

    operations = []
