# Generated by Django 4.0.3 on 2022-05-26 13:58

from django.db import migrations, models
from django.db.models.functions import Cast
import swapper


def populate_latest_revision(apps, schema_editor):
    Page = apps.get_model(swapper.get_model_name("wagtailcore", "Page"))
    if Page._meta.app_label != "wagtailcore" or Page._meta.model_name != "page":
        # Skip populating latest_revision_id if we are using a custom Page model.
        # These were only introduced after this migration was created (so if a custom Page model is
        # present we must be running this migration on a fresh database where no revisions exist)
        # and this way we can postpone adding the latest_revision_id field until after the
        # wagtailcore migrations have completed, rather than having messy interleaving of
        # migrations between wagtailcore and the app containing the custom Page model.
        return

    Revision = apps.get_model("wagtailcore.Revision")
    latest_revision_id = models.Subquery(
        Revision.objects.filter(
            content_type_id=models.OuterRef("content_type_id"),
            object_id=Cast(models.OuterRef("pk"), models.CharField()),
        )
        .order_by("-created_at", "-id")
        .values("pk")[:1]
    )
    Page.objects.all().update(latest_revision_id=latest_revision_id)


def populate_revision_object_str(apps, schema_editor):
    Revision = apps.get_model("wagtailcore.Revision")
    Revision.objects.all().update(object_str=models.F("content__title"))


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0074_revision_object_str"),
    ]

    operations = [
        migrations.RunPython(
            populate_latest_revision,
            migrations.RunPython.noop,
        ),
        migrations.RunPython(
            populate_revision_object_str,
            migrations.RunPython.noop,
        ),
    ]
