# Generated by Django 4.2.dev20221214105556 on 2022-12-14 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("wagtailcore", "0082_alter_workflowstate_content_type_notnull"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowContentType",
            fields=[
                (
                    "content_type",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="wagtail_workflow_content_type",
                        serialize=False,
                        to="contenttypes.contenttype",
                        verbose_name="content type",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_content_types",
                        to="wagtailcore.workflow",
                        verbose_name="workflow",
                    ),
                ),
            ],
        ),
    ]
