# Generated by Django 4.2.1 on 2023-06-14 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0084_add_default_page_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="grouppagepermission",
            name="permission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="auth.permission",
                verbose_name="permission",
            ),
        ),
    ]
