# Generated by Django 4.2.1 on 2023-06-14 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0084_add_default_page_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="grouppagepermission",
            name="permission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="auth.permission",
                verbose_name="permission",
            ),
        ),
        # Make permission_type nullable so the RemoveField operation will be reversible
        migrations.AlterField(
            model_name="grouppagepermission",
            name="permission_type",
            field=models.CharField(
                null=True,
                blank=True,
                choices=[
                    ("add", "Add/edit pages you own"),
                    ("edit", "Edit any page"),
                    ("publish", "Publish any page"),
                    ("bulk_delete", "Delete pages with children"),
                    ("lock", "Lock/unlock pages you've locked"),
                    ("unlock", "Unlock any page"),
                ],
                max_length=20,
                verbose_name="permission type",
            ),
        ),
    ]
