# Generated by Django 4.2.1 on 2023-06-14 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0086_populate_grouppagepermission_permission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grouppagepermission",
            name="permission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="auth.permission",
                verbose_name="permission",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="grouppagepermission",
            unique_together={("group", "page", "permission")},
        ),
        migrations.RemoveField(
            model_name="grouppagepermission",
            name="permission_type",
        ),
    ]
