# Generated by Django 4.0.10 on 2023-10-26 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="url_path",
            field=models.TextField(
                blank=True, editable=False, max_length=2000, verbose_name="URL path"
            ),
        ),
    ]
