# Generated by Django 5.2.7 on 2025-11-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("wagtailcore", "0095_groupsitepermission"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="referenceindex",
            index=models.Index(
                fields=["base_content_type", "object_id"],
                name="referenceindex_source_object",
            ),
        ),
        migrations.AddIndex(
            model_name="referenceindex",
            index=models.Index(
                fields=["to_content_type", "to_object_id"],
                name="referenceindex_target_object",
            ),
        ),
    ]
