# Generated by Django 6.0.3 on 2026-03-16 09:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="modellogentry",
            index=models.Index(
                fields=["uuid", "action", "-timestamp"],
                name="wagtailcore_uuid_d6363b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pagelogentry",
            index=models.Index(
                fields=["uuid", "action", "-timestamp"],
                name="wagtailcore_uuid_06a44d_idx",
            ),
        ),
    ]
