# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="canonical_url",
            field=models.URLField(
                blank=True,
                help_text="The canonical URL for this page. Leave blank to use the page's default URL.",
                max_length=255,
                verbose_name="canonical URL",
            ),
        ),
    ]
