# Generated by Django 6.0.1 on 2026-01-25 16:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='revision',
            index=models.Index(fields=['base_content_type', 'object_id', '-created_at'], name='revision_lookup_optimized'),
        ),
    ]
