# Generated by Django 6.0.2 on 2026-02-18 19:05

import wagtail.models.restriction_registry
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "wagtailcore",
            "0097_alter_collectionviewrestriction_restriction_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectionviewrestriction",
            name="restriction_type",
            field=models.CharField(
                choices=wagtail.models.restriction_registry.RestrictionRegistry.get_choices,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="pageviewrestriction",
            name="restriction_type",
            field=models.CharField(
                choices=wagtail.models.restriction_registry.RestrictionRegistry.get_choices,
                max_length=20,
            ),
        ),
    ]
