# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgres_search', '0002_add_autocomplete'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexentry',
            name='boost',
            field=models.FloatField(default=1),
        ),
    ]
