# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-03 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('postgres_search', '0003_add_row_boost'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexentry',
            name='index_name',
            field=models.TextField(db_index=True, default='default'),
        ),
        migrations.AlterUniqueTogether(
            name='indexentry',
            unique_together=set([('index_name', 'content_type', 'object_id')]),
        ),
    ]
