# Generated by Django 2.2.9 on 2020-01-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='generic_alt_text',
            field=models.CharField(blank=True, max_length=600, verbose_name='default alt text'),
        ),
    ]
