# Generated by Django 3.1.7 on 2021-04-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailembeds', '0008_allow_long_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='embed',
            name='cache_until',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
