# Generated by Django 6.0 on 2025-12-26 16:23

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('test', 1)], block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [(1, 'One'), (2, 'Two'), (3, 'Three')]}), 1: ('wagtail.blocks.StructBlock', [[('number', 0)]], {})})),
            ],
            options={
                'verbose_name': 'Test Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
