# Generated by Django 3.2.7 on 2021-09-20 15:35

from django.db import migrations
import wagtail.contrib.redirects.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirect',
            name='old_path',
            field=wagtail.contrib.redirects.fields.PatternField(db_index=True, max_length=255, verbose_name='redirect from'),
        ),
    ]
