# Generated by Django 3.0.8 on 2021-12-11 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='redirect',
            name='automatically_created',
            field=models.BooleanField(default=False, editable=False, verbose_name='automatically created'),
        ),
        migrations.AddField(
            model_name='redirect',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='redirect',
            name='trigger_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='redirect',
            name='trigger_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
