# Generated by Django 3.0.8 on 2022-01-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0007_add_autocreate_tracking_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='redirect',
            name='redirect_page_route_path',
            field=models.CharField(blank=True, max_length=255, verbose_name="target page route", help_text="Optionally specify a route on the target page to redirect to. Leave blank to redirect to the default page route.")
        ),
        migrations.RemoveField(
            model_name='redirect',
            name='trigger_content_type',
        ),
        migrations.RemoveField(
            model_name='redirect',
            name='trigger_id',
        ),
    ]
