# Generated by Django 5.0.8 on 2024-08-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailredirects", "0008_add_verbose_name_plural"),
    ]

    operations = [
        migrations.AddField(
            model_name="redirect",
            name="hash",
            field=models.UUIDField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AlterUniqueTogether(
            name="redirect",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="redirect",
            name="old_path",
            field=models.TextField(verbose_name="redirect from"),
        ),
    ]
