# Generated by Django 4.0.10 on 2023-10-29 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailredirects", "0008_add_verbose_name_plural"),
    ]

    operations = [
        migrations.AlterField(
            model_name="redirect",
            name="old_path",
            field=models.CharField(max_length=2000, verbose_name="redirect from"),
        ),
    ]
