# Generated by Django 5.0.8 on 2024-08-22 16:45

from django.db import migrations
from wagtail.contrib.redirects.models import Redirect as ImportedRedirect


def migrate_forwards(apps, schema_editor):
    Redirect = apps.get_model("wagtailredirects.Redirect")

    batch_size = 1500

    batch = []

    for redirect in Redirect.objects.all().only("id", "old_path", "site_id").iterator():

        redirect.hash = ImportedRedirect.get_redirect_hash(redirect.old_path)
        batch.append(redirect)

        if len(batch) == batch_size:
            # save and reset current batch
            Redirect.objects.bulk_update(batch, ["hash"])
            batch.clear()

    # save any leftovers
    if batch:
        Redirect.objects.bulk_update(batch, ["hash"])


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailredirects", "0009_redirect_hash_alter_redirect_old_path"),
    ]

    operations = [
        migrations.RunPython(migrate_forwards, migrations.RunPython.noop),
    ]
