# Generated by Django 5.0.8 on 2024-08-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailredirects", "0010_populate_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="redirect",
            name="hash",
            field=models.UUIDField(db_index=True, editable=False),
        ),
        migrations.AlterUniqueTogether(
            name="redirect",
            unique_together={("hash", "site")},
        ),
    ]
