# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailusers', '0005_make_related_name_wagtail_specific'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatar_images', verbose_name='Upload your custom avatar, preferred size is YYxZZ'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar_choice',
            field=models.CharField(choices=[('Default', 'Default'), ('Custom', 'Custom'), ('Gravatar', 'Gravatar')], default='Gravatar', max_length=10, verbose_name='Select avatar backend'),
        ),
    ]
