# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 19:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailusers', '0006_userprofile_prefered_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='prefered_language',
            new_name='preferred_language',
        ),
    ]
