# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='show_in_menus',
            field=models.BooleanField(default=True, help_text='Whether a link to this page will appear in automatically generated menus', verbose_name='show in menus'),
        ),
    ]
