# Generated by Django 2.2.12 on 2020-06-21 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0046_site_name_remove_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='uuid',
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
