# Generated by Django 3.1.1 on 2020-09-30 10:14

from django.db import migrations

from wagtail.core.models import Collection


def apply_collection_ordering(apps, schema_editor):
    Collection.fix_tree(fix_paths=True)


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0057_page_locale_fields_notnull'),
    ]

    operations = [
        migrations.RunPython(apply_collection_ordering, migrations.RunPython.noop),
    ]
