# Generated by Django 3.0.3 on 2021-04-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0063_move_position_into_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
