# Generated by Django 3.2 on 2021-05-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailuser', '0002_emailuser_permissionsmixin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailuser',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
