# Generated by Django 2.2.dev20181026000358 on 2018-10-27 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailembeds", "0003_capitalizeverbose"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="embed",
            options={"verbose_name": "embed", "verbose_name_plural": "embeds"},
        ),
    ]
