# Generated by Django 2.2.16 on 2020-11-01 20:03

from django.db import migrations
import wagtail.embeds.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailembeds', '0005_specify_thumbnail_url_max_length'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='embed',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='embed',
            name='thumbnail_url',
            field=wagtail.embeds.fields.URLField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='embed',
            name='url',
            field=wagtail.embeds.fields.URLField(),
        ),
    ]
