# Generated by Django 5.2.1 on 2025-07-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchtests', '0003_book_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publication_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
