# Generated by Django 4.0.3 on 2022-03-28 11:59

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailforms", "0004_add_verbose_name_plural"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formsubmission",
            name="form_data",
            field=models.JSONField(
                encoder=django.core.serializers.json.DjangoJSONEncoder
            ),
        ),
    ]
