# Generated by Django 5.1.4 on 2025-04-30 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailforms", "0005_alter_formsubmission_form_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsubmission',
            name='clean_name',
            field=models.CharField(blank=True, default='', help_text='Safe name of the form field, the label converted to ascii_snake_case', verbose_name='name'),
        ),
     
    ]
