# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modeladmintest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreebeardCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=250)),
            ],
        ),
    ]
