# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 23:35
from __future__ import absolute_import, unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0033_remove_golive_expiry_help_text'),
        ('modeladmintest', '0005_book_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDisplayOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_past_events', models.BooleanField(default=False)),
                ('per_page', models.IntegerField(default=10)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'event display options'
            },
        ),
    ]
