# Generated by Django 3.1.5 on 2021-01-15 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modeladmintest', '0009_relatedlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoloBookWithoutAuthorRelatedName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='modeladmintest.author')),
            ],
        ),
        migrations.CreateModel(
            name='BookWithoutAuthorRelatedName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='modeladmintest.author')),
            ],
        ),
    ]
