# Generated by Django 4.0.5 on 2022-07-18 07:15

from django.db import migrations, models
import wagtail.search.index


class Migration(migrations.Migration):

    dependencies = [
        ("snippetstests", "0007_translatablesnippet"),
    ]

    operations = [
        migrations.CreateModel(
            name="FilterableSnippet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                (
                    "country_code",
                    models.CharField(
                        choices=[
                            ("ID", "Indonesia"),
                            ("PH", "Philippines"),
                            ("UK", "United Kingdom"),
                        ],
                        max_length=2,
                    ),
                ),
            ],
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
