name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Here's a :candy: while we look into your'' first issue'
        pr-message: 'Kudos! You have successfully raised your'' first pr'
